// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A flow for generating actionable recommendations and KPIs based on a business diagnosis.
 *
 * - generateRecommendations - A function that generates recommendations and KPIs.
 * - GenerateRecommendationsInput - The input type for the generateRecommendationsInput function.
 * - GenerateRecommendationsOutput - The return type for the generateRecommendationsOutput function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateRecommendationsInputSchema = z.object({
  businessDiagnosis: z.string().describe('A comprehensive diagnosis of the business, including SWOT, PESTLE, and Porter\'s Five Forces analysis.'),
});
export type GenerateRecommendationsInput = z.infer<typeof GenerateRecommendationsInputSchema>;

const GenerateRecommendationsOutputSchema = z.object({
  recommendations: z.array(z.string()).describe('A list of actionable recommendations for improving the business.'),
  kpis: z.array(z.string()).describe('A list of key performance indicators (KPIs) for tracking the success of the recommendations.'),
});
export type GenerateRecommendationsOutput = z.infer<typeof GenerateRecommendationsOutputSchema>;

export async function generateRecommendations(input: GenerateRecommendationsInput): Promise<GenerateRecommendationsOutput> {
  return generateRecommendationsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateRecommendationsPrompt',
  input: {schema: GenerateRecommendationsInputSchema},
  output: {schema: GenerateRecommendationsOutputSchema},
  prompt: `You are a business consultant specializing in providing actionable recommendations and KPIs based on a business diagnosis.

  Based on the following business diagnosis, generate a list of actionable recommendations and KPIs.

  Business Diagnosis: {{{businessDiagnosis}}}

  Recommendations should be specific, measurable, achievable, relevant, and time-bound (SMART).
  KPIs should be directly related to the recommendations and should be measurable.

  Ensure the output is well-formatted and easy to understand.

  Example:
  Recommendations: ["Improve marketing strategy by focusing on digital channels", "Optimize supply chain to reduce costs"]
  KPIs: ["Increase website traffic by 20% in the next quarter", "Reduce supply chain costs by 15% in the next year"]
  `,
});

const generateRecommendationsFlow = ai.defineFlow(
  {
    name: 'generateRecommendationsFlow',
    inputSchema: GenerateRecommendationsInputSchema,
    outputSchema: GenerateRecommendationsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
